services:
  mongo:
    image: mongo:latest
    container_name: cloak-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloak-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/cloak-service
    depends_on:
      - mongo

volumes:
  mongo-data:
